# Ensure this uses PHP
language: php

sudo: false
dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/phpunit-bin

install:
  - nvm install 6 && nvm use 6
  - export DEV_LIB_PATH=dev-lib
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh

jobs:
  include:
    - stage: test
      php: "7.2"
      env: WP_VERSION=trunk
    - php: "5.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=composer,phpcs
    - php: "5.4"
      env: WP_VERSION=4.7    DEV_LIB_SKIP=composer,phpcs
    - php: "5.5"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "5.6"
      env: WP_VERSION=4.8    DEV_LIB_SKIP=phpcs
    - php: "5.6"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.0"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
    - php: "7.1"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs
