version: 2.1

orbs:
  php: circleci/php@1.1

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: svn co https://plugins.svn.wordpress.org/adapter-responsive-video --depth=empty .

workflows:
  test-deploy:
    jobs:
      - php/test:
          test-command: lint
          version: '8.0'
      - deploy:
          requires:
            - php/test
